(() => {
  'use strict';
  const $ = (s, r = document) => r.querySelector(s);
  const $$ = (s, r = document) => [...r.querySelectorAll(s)];
  const safe = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const toast = msg => {
    const t = $('#toast'); if (!t) return;
    t.textContent = msg; t.classList.add('show');
    clearTimeout(window.__supportopsV2Toast);
    window.__supportopsV2Toast = setTimeout(() => t.classList.remove('show'), 2200);
  };
  const modal = (title, body, actions='') => {
    const bg=$('#modalBg'), h=$('#modalTitle'), b=$('#modalBody'), a=$('#modalActions');
    if(!bg||!h||!b||!a)return;
    h.textContent=title; b.innerHTML=body; a.innerHTML=actions||'<button class="btn" data-close-modal>Fermer</button>'; bg.hidden=false;
  };

  const state = {
    incidents:[
      {id:'INC-2056',title:'MFA impossible pour direction finance',service:'Identity',priority:'P1',owner:'Aina R.',age:'18 min',status:'Nouveau',risk:'Élevé'},
      {id:'INC-2053',title:'Saturation file impression production',service:'Workplace',priority:'P2',owner:'Hery R.',age:'46 min',status:'En cours',risk:'Moyen'},
      {id:'INC-2051',title:'Perte intermittente tunnel site-to-site',service:'Network',priority:'P2',owner:'Noro T.',age:'1h08',status:'En cours',risk:'Élevé'},
      {id:'INC-2049',title:'Erreur 502 portail fournisseurs',service:'Application',priority:'P2',owner:'Miora A.',age:'1h42',status:'En cours',risk:'Moyen'}
    ],
    problems:[
      {id:'PRB-017',title:'Instabilité VPN récurrente',incidents:6,root:'Résolution DNS / tunnel',status:'Investigation'},
      {id:'PRB-014',title:'Croissance disque FILE-01',incidents:4,root:'Rétention logs',status:'Known Error'},
      {id:'PRB-012',title:'Latence API legacy',incidents:9,root:'Pool connexion saturé',status:'Planifié'}
    ],
    executions:[
      {id:'RUN-8831',runbook:'Network Diagnostic',target:'INC-2048',by:'Aina R.',status:'Succès',duration:'00:42',time:'12:51'},
      {id:'RUN-8829',runbook:'HTTP Synthetic Probe',target:'ALT-901',by:'system',status:'Échec',duration:'00:31',time:'12:47'},
      {id:'RUN-8826',runbook:'Disk Capacity Triage',target:'INC-2037',by:'Hery R.',status:'Succès',duration:'01:08',time:'12:38'},
      {id:'RUN-8822',runbook:'DNS Resolver Check',target:'INC-2032',by:'Aina R.',status:'Succès',duration:'00:36',time:'12:21'}
    ],
    rules:[
      {id:'RULE-21',name:'VPN timeout → Network Diagnostic',trigger:'category=VPN + timeout',runbook:'Network Diagnostic',mode:'Auto diagnostic',active:true},
      {id:'RULE-18',name:'Disk > 85% → Disk Capacity Triage',trigger:'disk_usage > 85',runbook:'Disk Capacity Triage',mode:'Approval required',active:true},
      {id:'RULE-14',name:'HTTP 5xx → Synthetic Probe',trigger:'http_status >= 500',runbook:'HTTP Synthetic Probe',mode:'Auto diagnostic',active:true},
      {id:'RULE-09',name:'P1 → Major Incident workflow',trigger:'priority=P1',runbook:'Incident Coordination',mode:'Workflow',active:false}
    ],
    approvals:[
      {id:'APR-104',action:'Restart service applicatif',target:'APP-BILLING-01',requester:'Noro T.',risk:'Moyen'},
      {id:'APR-101',action:'Nettoyage fichiers temporaires',target:'FILE-01',requester:'Hery R.',risk:'Faible'}
    ],
    services:[
      {name:'Portal ITSM',team:'Support',status:'Up',latency:'118 ms',slo:'99,9%',errors:'0,12%'},
      {name:'SupportOps API',team:'Automation',status:'Up',latency:'84 ms',slo:'99,95%',errors:'0,08%'},
      {name:'PostgreSQL',team:'Platform',status:'Warning',latency:'286 ms',slo:'99,9%',errors:'0,43%'},
      {name:'API Legacy',team:'Apps',status:'Down',latency:'—',slo:'99,5%',errors:'100%'},
      {name:'Redis',team:'Platform',status:'Up',latency:'7 ms',slo:'99,9%',errors:'0,01%'}
    ],
    alerts:[
      {id:'ALT-911',title:'CPU worker > 90%',source:'Prometheus',route:'Platform',state:'Active',corr:'INC-2057'},
      {id:'ALT-909',title:'VPN packet loss > 12%',source:'Network exporter',route:'Network',state:'Active',corr:'INC-2051'},
      {id:'ALT-906',title:'SLA P1 à 80% consommé',source:'ITSM',route:'Support Lead',state:'Correlated',corr:'INC-2048'},
      {id:'ALT-903',title:'Backup age > 26h',source:'Backup exporter',route:'Infrastructure',state:'Suppressed',corr:'—'}
    ],
    articles:[
      {id:'KB-0041',title:'MFA — diagnostic premier niveau',type:'Article',owner:'Miora A.',review:'2026-09-04',status:'Publié'},
      {id:'KE-0018',title:'Timeout tunnel VPN lors bascule ISP',type:'Known Error',owner:'Aina R.',review:'2026-08-29',status:'Publié'},
      {id:'KB-0038',title:'Procédure Incident Majeur P1',type:'Article',owner:'Support Lead',review:'2026-09-12',status:'En revue'},
      {id:'KE-0015',title:'FILE-01 : croissance logs applicatifs',type:'Known Error',owner:'Hery R.',review:'2026-08-25',status:'Brouillon'}
    ],
    tasks:{Backlog:['Auto-remediation M365','Vendor scorecard'],Todo:['Problem workflow','Change calendar'],Progress:['Alert deduplication','KB relevance scoring'],Review:['SLA policy editor'],Done:['Incident queue','Runbook approvals','Observability drilldown']},
    risks:[
      {id:'RSK-08',risk:'Trop d’automatisation sans garde-fou',impact:'Élevé',prob:'Faible',owner:'Automation Lead',mitigation:'Approval + dry-run'},
      {id:'RSK-06',risk:'Faux positifs monitoring',impact:'Moyen',prob:'Moyenne',owner:'Platform',mitigation:'Corrélation + fenêtre'},
      {id:'RSK-03',risk:'Knowledge Base non maintenue',impact:'Moyen',prob:'Moyenne',owner:'Support Lead',mitigation:'Cycle de review'}
    ],
    vendors:[
      {name:'Cloud Provider A',service:'IaaS',sla:'99,95%',renewal:'2026-11-30',score:'92/100'},
      {name:'ISP Principal',service:'WAN',sla:'99,5%',renewal:'2027-01-15',score:'86/100'},
      {name:'Endpoint Security',service:'EDR',sla:'99,9%',renewal:'2026-10-04',score:'94/100'}
    ]
  };

  const tabs = {
    dashboard:[['overview','Vue opérationnelle'],['activity','Activité live'],['service','Service review']],
    incidents:[['overview','File ITSM'],['major','Incidents majeurs'],['problems','Problem candidates'],['postmortem','Post-mortems']],
    automation:[['overview','Bibliothèque'],['executions','Exécutions'],['rules','Rules Engine'],['approvals','Approbations']],
    sla:[['overview','Vue SLA'],['policies','Politiques'],['breaches','Breaches'],['matrix','Service matrix']],
    monitoring:[['overview','Services'],['metrics','Métriques'],['dependencies','Dépendances'],['synthetics','Synthetics']],
    alerts:[['overview','Alertes actives'],['correlated','Corrélées'],['suppressed','Silencées'],['routing','Routage']],
    knowledge:[['overview','Articles'],['known','Known Errors'],['problems','Problem Records'],['review','Review Queue']],
    analytics:[['overview','Executive'],['roi','Automation ROI'],['sla','SLA'],['team','Équipe'],['trends','Tendances']],
    project:[['overview','Programme'],['roadmap','Roadmap'],['board','Kanban'],['risks','Risques'],['vendors','Fournisseurs']],
    architecture:[['overview','Architecture'],['flow','Data Flow'],['security','Sécurité'],['deployment','Déploiement'],['integrations','Intégrations']]
  };

  function installTabs(pageId){
    const page=$(`#${pageId}`); if(!page || page.dataset.v2Enhanced)return;
    page.dataset.v2Enhanced='true';
    const original=[...page.children];
    const legacy=document.createElement('div');
    legacy.className='v2-panel active'; legacy.dataset.v2Panel='overview';
    original.forEach(n=>legacy.appendChild(n));
    const bar=document.createElement('div'); bar.className='v2-tabs glass';
    bar.innerHTML=tabs[pageId].map((t,i)=>`<button type="button" class="${i===0?'active':''}" data-v2-tab="${t[0]}" data-v2-page="${pageId}">${safe(t[1])}</button>`).join('');
    page.append(bar,legacy);
    tabs[pageId].slice(1).forEach(t=>{
      const p=document.createElement('div');p.className='v2-panel';p.dataset.v2Panel=t[0];p.innerHTML=panelMarkup(pageId,t[0]);page.appendChild(p);
    });
  }

  function panelMarkup(page,view){
    const key=`${page}:${view}`;
    const m={
      'dashboard:activity':()=>`<div class="v2-grid two"><article class="card glass"><div class="card-head"><div><span class="eyebrow">Event stream</span><h3>Activité opérationnelle en temps quasi-réel</h3></div><div class="seg mini"><button class="active" data-v2-range="1h">1h</button><button data-v2-range="6h">6h</button><button data-v2-range="24h">24h</button></div></div><div class="v2-timeline" id="v2Activity"></div></article><article class="card glass"><span class="eyebrow">Workload</span><h3>Répartition par domaine</h3><div class="v2-workload" id="v2Workload"></div></article></div>`,
      'dashboard:service':()=>`<div class="v2-grid two"><article class="card glass"><span class="eyebrow">Service review</span><h3>Résumé hebdomadaire</h3><div class="v2-scorecards" id="v2ServiceReview"></div></article><article class="card glass"><span class="eyebrow">Actions</span><h3>Plan d'amélioration</h3><div class="v2-action-list" id="v2ActionPlan"></div></article></div>`,
      'incidents:major':()=>`<div class="metric-grid four"><article class="metric glass"><small>Major actifs</small><strong>2</strong><span>P1 coordonnés</span></article><article class="metric glass"><small>Bridge ouvert</small><strong>1</strong><span>war room</span></article><article class="metric glass"><small>Communications</small><strong>6</strong><span>stakeholders</span></article><article class="metric glass"><small>Prochain update</small><strong>13:45</strong><span>dans 17 min</span></article></div><article class="card glass section-gap"><div class="card-head"><div><span class="eyebrow">Major incident command</span><h3>Coordination P1</h3></div><button class="btn primary" data-v2-new-major>+ Déclarer majeur</button></div><div class="v2-major-list" id="v2MajorList"></div></article>`,
      'incidents:problems':()=>`<article class="card glass"><div class="card-head"><div><span class="eyebrow">Problem Management</span><h3>Clusters d'incidents récurrents</h3></div><button class="btn" data-v2-recluster>Recalculer les candidats</button></div><div class="tablewrap"><table><thead><tr><th>ID</th><th>Problème</th><th>Incidents liés</th><th>Cause probable</th><th>Statut</th><th></th></tr></thead><tbody id="v2ProblemRows"></tbody></table></div></article>`,
      'incidents:postmortem':()=>`<div class="v2-grid two"><article class="card glass"><span class="eyebrow">Post-mortems</span><h3>Revue sans blâme</h3><div class="v2-postmortems" id="v2Postmortems"></div></article><article class="card glass"><span class="eyebrow">Template</span><h3>Structure standard</h3><ol class="v2-checklist"><li>Impact & durée</li><li>Timeline factuelle</li><li>Cause racine / facteurs contributifs</li><li>Ce qui a bien fonctionné</li><li>Actions correctives avec owner</li></ol><button class="btn primary" data-v2-new-postmortem>Créer un post-mortem fictif</button></article></div>`,
      'automation:executions':()=>`<article class="card glass"><div class="card-head"><div><span class="eyebrow">Execution history</span><h3>Historique des runbooks</h3></div><div class="v2-actions"><button class="btn" data-v2-export="executions">Exporter CSV</button><button class="btn primary" data-v2-sim-run>+ Simuler une exécution</button></div></div><div class="tablewrap"><table><thead><tr><th>Run</th><th>Runbook</th><th>Cible</th><th>Lancé par</th><th>Statut</th><th>Durée</th><th>Heure</th></tr></thead><tbody id="v2ExecutionRows"></tbody></table></div></article>`,
      'automation:rules':()=>`<div class="v2-grid two"><article class="card glass"><div class="card-head"><div><span class="eyebrow">Rules Engine</span><h3>Règles de déclenchement</h3></div><button class="btn primary" data-v2-new-rule>+ Nouvelle règle</button></div><div id="v2RuleList" class="v2-rule-list"></div></article><article class="card glass"><span class="eyebrow">Guardrails</span><h3>Contrôles avant exécution</h3><div class="v2-guardrails"><span>✓ Dry-run par défaut</span><span>✓ RBAC par runbook</span><span>✓ Approval pour remédiation</span><span>✓ Journal d'audit</span><span>✓ Timeout & rollback simulé</span><span>✓ Fenêtre de maintenance</span></div></article></div>`,
      'automation:approvals':()=>`<div class="metric-grid four"><article class="metric glass"><small>En attente</small><strong id="v2ApprovalCount">2</strong><span>remédiations</span></article><article class="metric glass"><small>Approuvées 24h</small><strong>11</strong><span>contrôlées</span></article><article class="metric glass"><small>Refusées</small><strong>1</strong><span>risque élevé</span></article><article class="metric glass"><small>Auto-diagnostics</small><strong>68</strong><span>sans changement</span></article></div><article class="card glass section-gap"><h3>File d'approbation</h3><div id="v2ApprovalList" class="v2-approval-list"></div></article>`,
      'sla:policies':()=>`<div class="v2-grid two"><article class="card glass"><div class="card-head"><div><span class="eyebrow">Policies</span><h3>Catalogue SLA editable en démo</h3></div><button class="btn primary" data-v2-new-policy>+ Politique</button></div><div id="v2PolicyEditor"></div></article><article class="card glass"><span class="eyebrow">Calendrier</span><h3>Couverture de service</h3><div class="v2-coverage"><div><b>P1</b><span>24×7</span></div><div><b>P2</b><span>06:00–22:00</span></div><div><b>P3/P4</b><span>Heures ouvrées</span></div></div></article></div>`,
      'sla:breaches':()=>`<article class="card glass"><div class="card-head"><div><span class="eyebrow">Breach analysis</span><h3>Dépassements et causes</h3></div><button class="btn" data-v2-export="breaches">Exporter</button></div><div id="v2BreachList" class="v2-breach-list"></div></article>`,
      'sla:matrix':()=>`<article class="card glass"><span class="eyebrow">Service matrix</span><h3>Engagement par service</h3><div class="tablewrap"><table><thead><tr><th>Service</th><th>Tier</th><th>Disponibilité</th><th>P1 Resolve</th><th>P2 Resolve</th><th>Owner</th></tr></thead><tbody id="v2SlaMatrix"></tbody></table></div></article>`,
      'monitoring:metrics':()=>`<div class="v2-grid two"><article class="card glass"><div class="card-head"><div><span class="eyebrow">Explorer</span><h3>Metric Explorer</h3></div><select id="v2MetricSelect"><option>support_mttr_seconds</option><option>support_sla_compliance</option><option>automation_runs_total</option><option>service_availability</option></select></div><div class="v2-spark" id="v2MetricSpark"></div><div class="v2-query"><code id="v2PromQuery">histogram_quantile(0.95, support_mttr_seconds_bucket)</code><button class="btn compact" data-v2-copy-query>Copier</button></div></article><article class="card glass"><span class="eyebrow">Cardinality</span><h3>Top séries</h3><div id="v2SeriesList" class="v2-series"></div></article></div>`,
      'monitoring:dependencies':()=>`<article class="card glass"><div class="card-head"><div><span class="eyebrow">Dependency map</span><h3>Relations entre services</h3></div><button class="btn" data-v2-dependency-mode>Mode impact</button></div><div class="v2-dependency-map" id="v2DependencyMap"></div><div class="v2-dependency-detail" id="v2DependencyDetail">Sélectionnez un service pour voir ses dépendances.</div></article>`,
      'monitoring:synthetics':()=>`<div class="v2-grid two"><article class="card glass"><div class="card-head"><div><span class="eyebrow">Synthetic checks</span><h3>Probes applicatives</h3></div><button class="btn primary" data-v2-new-probe>+ Probe</button></div><div id="v2ProbeList"></div></article><article class="card glass"><span class="eyebrow">Dernier run</span><h3>Waterfall simulé</h3><div class="v2-waterfall"><span style="--w:18%"><b>DNS</b><i>21 ms</i></span><span style="--w:26%"><b>TCP/TLS</b><i>34 ms</i></span><span style="--w:56%"><b>TTFB</b><i>71 ms</i></span></div></article></div>`,
      'alerts:correlated':()=>`<article class="card glass"><span class="eyebrow">Correlation</span><h3>Alertes regroupées par incident</h3><div id="v2Correlations" class="v2-correlation-list"></div></article>`,
      'alerts:suppressed':()=>`<div class="v2-grid two"><article class="card glass"><div class="card-head"><div><span class="eyebrow">Silences</span><h3>Alertes supprimées temporairement</h3></div><button class="btn primary" data-v2-new-silence>+ Silence</button></div><div id="v2SilenceList"></div></article><article class="card glass"><span class="eyebrow">Policy</span><h3>Règles de suppression</h3><div class="v2-guardrails"><span>Maintenance planifiée</span><span>Déduplication 5 min</span><span>Inhibition parent → child</span><span>Pas de silence P1 sans owner</span></div></article></div>`,
      'alerts:routing':()=>`<article class="card glass"><div class="card-head"><div><span class="eyebrow">Routing</span><h3>Règles d'escalade</h3></div><button class="btn primary" data-v2-new-route>+ Route</button></div><div id="v2RoutingTable"></div></article>`,
      'knowledge:known':()=>`<article class="card glass"><div class="card-head"><div><span class="eyebrow">Known Error Database</span><h3>Erreurs connues & workarounds</h3></div><button class="btn primary" data-v2-new-known>+ Known Error</button></div><div id="v2KnownRows" class="v2-known-list"></div></article>`,
      'knowledge:problems':()=>`<div class="v2-grid two"><article class="card glass"><span class="eyebrow">Problem records</span><h3>Problèmes reliés à la connaissance</h3><div id="v2KbProblems"></div></article><article class="card glass"><span class="eyebrow">Knowledge loop</span><h3>Incident → Problem → Known Error → Article</h3><div class="flowline vertical"><b>Incident cluster</b><i>↓</i><b>Problem Record</b><i>↓</i><b>Root cause</b><i>↓</i><b>Known Error</b><i>↓</i><b>Knowledge Article</b></div></article></div>`,
      'knowledge:review':()=>`<article class="card glass"><span class="eyebrow">Governance</span><h3>File de revue documentaire</h3><div id="v2ReviewQueue" class="v2-review-list"></div></article>`,
      'analytics:roi':()=>`<div class="metric-grid four"><article class="metric glass"><small>Heures libérées</small><strong>142h</strong><span>/ mois</span></article><article class="metric glass"><small>Coût évité simulé</small><strong>8,4M Ar</strong><span>/ trimestre</span></article><article class="metric glass"><small>Auto-résolution</small><strong>41%</strong><span>éligibles</span></article><article class="metric glass"><small>Taux succès</small><strong>97,6%</strong><span>runbooks</span></article></div><div class="v2-grid two section-gap"><article class="card glass"><h3>ROI par runbook</h3><div id="v2RoiRunbooks"></div></article><article class="card glass"><h3>Hypothèses de calcul</h3><div class="v2-assumptions"><span>Temps technicien économisé</span><span>Volume mensuel simulé</span><span>Échec = revue manuelle</span><span>Aucune donnée financière Datajet</span></div></article></div>`,
      'analytics:sla':()=>`<article class="card glass"><div class="card-head"><div><span class="eyebrow">SLA analytics</span><h3>Conformité par service</h3></div><div class="seg mini"><button class="active" data-v2-analytics-range="30">30j</button><button data-v2-analytics-range="90">90j</button></div></div><div id="v2SlaAnalytics"></div></article>`,
      'analytics:team':()=>`<div class="v2-grid two"><article class="card glass"><h3>Charge équipe</h3><div id="v2TeamLoad"></div></article><article class="card glass"><h3>Qualité de traitement</h3><div id="v2TeamQuality"></div></article></div>`,
      'analytics:trends':()=>`<article class="card glass"><div class="card-head"><div><span class="eyebrow">Trends</span><h3>12 semaines simulées</h3></div><button class="btn" data-v2-export="trends">Exporter CSV</button></div><div class="v2-trend-chart" id="v2TrendChart"></div></article>`,
      'project:roadmap':()=>`<article class="card glass"><div class="card-head"><div><span class="eyebrow">Roadmap</span><h3>Évolution du programme</h3></div><button class="btn primary" data-v2-new-milestone>+ Jalons</button></div><div class="v2-roadmap" id="v2Roadmap"></div></article>`,
      'project:board':()=>`<article class="card glass"><div class="card-head"><div><span class="eyebrow">Delivery board</span><h3>Kanban interactif de démonstration</h3></div><button class="btn primary" data-v2-new-task>+ Tâche</button></div><div class="v2-kanban" id="v2Kanban"></div></article>`,
      'project:risks':()=>`<article class="card glass"><div class="card-head"><div><span class="eyebrow">Risk register</span><h3>Risques du programme</h3></div><button class="btn primary" data-v2-new-risk>+ Risque</button></div><div class="tablewrap"><table><thead><tr><th>ID</th><th>Risque</th><th>Impact</th><th>Probabilité</th><th>Owner</th><th>Mitigation</th></tr></thead><tbody id="v2RiskRows"></tbody></table></div></article>`,
      'project:vendors':()=>`<div class="v2-grid two"><article class="card glass"><span class="eyebrow">Vendor Management</span><h3>Fournisseurs technologiques</h3><div id="v2VendorList"></div></article><article class="card glass"><span class="eyebrow">Negotiation pack</span><h3>Points suivis</h3><div class="v2-guardrails"><span>SLA & pénalités</span><span>Renouvellement</span><span>Support & escalade</span><span>Coût total</span><span>Réversibilité</span><span>Performance fournisseur</span></div></article></div>`,
      'architecture:flow':()=>`<article class="card glass"><span class="eyebrow">Data Flow</span><h3>Flux d'un incident automatisé</h3><div class="v2-flow-arch" id="v2FlowArch"></div></article>`,
      'architecture:security':()=>`<div class="v2-grid two"><article class="card glass"><span class="eyebrow">Security model</span><h3>Contrôles de sécurité</h3><div id="v2SecurityControls" class="v2-control-grid"></div></article><article class="card glass"><span class="eyebrow">RBAC</span><h3>Matrice de permissions</h3><div id="v2RbacMatrix"></div></article></div>`,
      'architecture:deployment':()=>`<article class="card glass"><span class="eyebrow">Deployment topology</span><h3>Environnements & services</h3><div class="v2-deploy" id="v2Deploy"></div></article>`,
      'architecture:integrations':()=>`<article class="card glass"><span class="eyebrow">Integrations</span><h3>Connecteurs fonctionnels simulés</h3><div id="v2Integrations" class="v2-integration-grid"></div></article>`
    };
    return (m[key]||(()=>'<article class="card glass"><p class="muted">Vue V2 en cours de rendu.</p></article>'))();
  }

  function renderV2(){
    const activity=[['12:58','Alert Center','ALT-911 corrélée à INC-2057','warning'],['12:54','Automation','RUN-8831 terminé avec succès','success'],['12:49','ITSM','INC-2056 déclaré P1','critical'],['12:41','Knowledge','KB-0041 publiée','info'],['12:33','SLA','Escalade automatique P1 déclenchée','warning'],['12:21','Monitoring','PostgreSQL latency warning','warning']];
    const a=$('#v2Activity');if(a)a.innerHTML=activity.map(x=>`<div><time>${x[0]}</time><i class="${x[3]}"></i><p><b>${x[1]}</b><span>${x[2]}</span></p></div>`).join('');
    const wl=$('#v2Workload');if(wl)wl.innerHTML=[['Network',78],['Identity',56],['Application',69],['Workplace',42],['Platform',63]].map(x=>`<div><span>${x[0]}</span><b><i style="--w:${x[1]}%"></i></b><em>${x[1]}%</em></div>`).join('');
    const sr=$('#v2ServiceReview');if(sr)sr.innerHTML=[['SLA','96,8%','+1,8 pt'],['MTTR','2h44','-35%'],['Automation success','97,6%','+2,1 pt'],['Backlog','42','-11%']].map(x=>`<div><span>${x[0]}</span><strong>${x[1]}</strong><em>${x[2]}</em></div>`).join('');
    const ap=$('#v2ActionPlan');if(ap)ap.innerHTML=[['P1','Stabiliser API legacy','Apps','2026-08-21'],['P2','Réduire faux positifs DB','Platform','2026-08-23'],['P2','Publier KB MFA','Support','2026-08-25'],['P3','Étendre runbook M365','Automation','2026-08-30']].map(x=>`<button data-v2-action-detail="${safe(x[1])}"><span class="pri ${x[0].toLowerCase()}">${x[0]}</span><div><b>${x[1]}</b><small>${x[2]} · ${x[3]}</small></div></button>`).join('');
    const major=$('#v2MajorList');if(major)major.innerHTML=[['MI-044','VPN entreprise indisponible','P1','18 min','Bridge actif','Prochain update 13:45'],['MI-042','Portail facturation indisponible','P1','31 min','Diagnostic','Stakeholders informés']].map(x=>`<article><div><span class="pri p1">${x[2]}</span><b>${x[0]} · ${x[1]}</b><small>${x[3]} · ${x[4]}</small></div><button class="btn compact" data-v2-major="${x[0]}">${x[5]}</button></article>`).join('');
    const pr=$('#v2ProblemRows');if(pr)pr.innerHTML=state.problems.map(p=>`<tr><td><b>${p.id}</b></td><td>${p.title}</td><td>${p.incidents}</td><td>${p.root}</td><td><span class="badge ${p.status==='Known Error'?'ok':'warn'}">${p.status}</span></td><td><button class="btn compact" data-v2-problem="${p.id}">Ouvrir</button></td></tr>`).join('');
    const pm=$('#v2Postmortems');if(pm)pm.innerHTML=[['PM-032','API facturation indisponible','42 min','3 actions'],['PM-029','VPN site principal','58 min','5 actions'],['PM-026','Incident stockage','1h14','4 actions']].map(x=>`<button data-v2-postmortem="${x[0]}"><div><b>${x[0]} · ${x[1]}</b><span>Impact ${x[2]}</span></div><em>${x[3]}</em></button>`).join('');
    const ex=$('#v2ExecutionRows');if(ex)ex.innerHTML=state.executions.map(r=>`<tr><td><b>${r.id}</b></td><td>${r.runbook}</td><td>${r.target}</td><td>${r.by}</td><td><span class="badge ${r.status==='Succès'?'ok':'danger'}">${r.status}</span></td><td>${r.duration}</td><td>${r.time}</td></tr>`).join('');
    const rl=$('#v2RuleList');if(rl)rl.innerHTML=state.rules.map(r=>`<article><button class="v2-switch ${r.active?'on':''}" data-v2-toggle-rule="${r.id}" aria-label="Activer ou désactiver"></button><div><b>${r.name}</b><span>${r.trigger}</span><small>${r.runbook} · ${r.mode}</small></div><button class="btn compact" data-v2-rule="${r.id}">Éditer</button></article>`).join('');
    renderApprovals();
    const pe=$('#v2PolicyEditor');if(pe)pe.innerHTML=[['P1 Critical','15 min','2 h','24×7'],['P2 High','30 min','4 h','06–22'],['P3 Medium','2 h','8 h','HO'],['P4 Low','4 h','24 h','HO']].map((x,i)=>`<div class="v2-policy"><b>${x[0]}</b><label>Prise en charge<input value="${x[1]}"></label><label>Résolution<input value="${x[2]}"></label><label>Couverture<input value="${x[3]}"></label><button class="btn compact" data-v2-save-policy="${i}">Sauver</button></div>`).join('');
    const bl=$('#v2BreachList');if(bl)bl.innerHTML=[['INC-1988','P2','Database','+18 min','Attente fournisseur'],['INC-1962','P3','Workplace','+42 min','Mauvaise catégorisation']].map(x=>`<article><span class="pri ${x[1].toLowerCase()}">${x[1]}</span><div><b>${x[0]} · ${x[2]}</b><span>${x[4]}</span></div><strong>${x[3]}</strong><button class="btn compact" data-v2-breach="${x[0]}">Analyser</button></article>`).join('');
    const sm=$('#v2SlaMatrix');if(sm)sm.innerHTML=[['Remote Access','Tier 1','99,9%','2h','4h','Network'],['Billing API','Tier 1','99,95%','2h','4h','Apps'],['File Services','Tier 2','99,5%','4h','8h','Infrastructure'],['Workplace','Tier 3','99,0%','4h','8h','Support']].map(x=>`<tr>${x.map((v,i)=>`<td>${i===0?`<b>${v}</b>`:v}</td>`).join('')}</tr>`).join('');
    renderMetricSpark();
    const sl=$('#v2SeriesList');if(sl)sl.innerHTML=[['http_requests_total','12 481'],['node_cpu_seconds_total','4 204'],['support_ticket_events_total','2 919'],['automation_runs_total','1 284']].map(x=>`<div><b>${x[0]}</b><span>${x[1]} séries</span></div>`).join('');
    const dm=$('#v2DependencyMap');if(dm)dm.innerHTML=['Portal ITSM','SupportOps API','PostgreSQL','Redis','Prometheus','API Legacy'].map((s,i)=>`<button class="node n${i}" data-v2-dependency="${s}"><i></i><b>${s}</b></button>`).join('')+'<svg viewBox="0 0 800 320" aria-hidden="true"><path d="M110 80 C230 80 230 150 350 150"/><path d="M350 150 C480 150 480 70 650 70"/><path d="M350 150 C480 150 480 180 650 180"/><path d="M110 250 C230 250 230 150 350 150"/><path d="M350 150 C480 150 480 270 650 270"/></svg>';
    const pl=$('#v2ProbeList');if(pl)pl.innerHTML=[['Login Portal','HTTPS','30s','99,99%'],['Billing API','API','60s','98,81%'],['VPN Endpoint','TCP','60s','99,72%'],['DNS Internal','DNS','30s','99,98%']].map(x=>`<article><div><b>${x[0]}</b><span>${x[1]} · ${x[2]}</span></div><strong>${x[3]}</strong><button class="btn compact" data-v2-probe="${x[0]}">Tester</button></article>`).join('');
    const co=$('#v2Correlations');if(co)co.innerHTML=[['INC-2051','3 alertes réseau','Packet loss + tunnel + latency'],['INC-2048','2 alertes SLA/Identity','SLA risk + auth failures'],['INC-2041','4 alertes DB','Latency + connections + slow queries']].map(x=>`<article><div><b>${x[0]}</b><span>${x[1]}</span></div><p>${x[2]}</p><button class="btn compact" data-v2-correlation="${x[0]}">Voir le groupe</button></article>`).join('');
    const si=$('#v2SilenceList');if(si)si.innerHTML=[['SIL-041','Maintenance réseau site B','18:00–20:00','Network'],['SIL-038','Patch PostgreSQL','22:00–23:30','Platform']].map(x=>`<article><div><b>${x[0]} · ${x[1]}</b><span>${x[2]} · ${x[3]}</span></div><button class="btn compact" data-v2-end-silence="${x[0]}">Terminer</button></article>`).join('');
    const rt=$('#v2RoutingTable');if(rt)rt.innerHTML=[['Critical + Network','Network On-call','Immédiat','SMS + Chat'],['P1 SLA risk','Support Lead','Immédiat','Chat + Email'],['DB Warning','Platform','5 min','Chat'],['Info Backup','Infrastructure','15 min','Email']].map((x,i)=>`<article><div><b>${x[0]}</b><span>${x[1]} · délai ${x[2]} · ${x[3]}</span></div><button class="btn compact" data-v2-route="${i}">Modifier</button></article>`).join('');
    const kr=$('#v2KnownRows');if(kr)kr.innerHTML=state.articles.filter(a=>a.type==='Known Error').map(a=>`<article><div><b>${a.id} · ${a.title}</b><span>Owner ${a.owner} · revue ${a.review}</span></div><span class="badge ok">${a.status}</span><button class="btn compact" data-v2-article="${a.id}">Ouvrir</button></article>`).join('');
    const kp=$('#v2KbProblems');if(kp)kp.innerHTML=state.problems.map(p=>`<button data-v2-problem="${p.id}"><span><b>${p.id} · ${p.title}</b><small>${p.incidents} incidents · ${p.status}</small></span><em>→</em></button>`).join('');
    const rq=$('#v2ReviewQueue');if(rq)rq.innerHTML=state.articles.map(a=>`<article><div><b>${a.id} · ${a.title}</b><span>${a.owner} · prochaine revue ${a.review}</span></div><span class="badge ${a.status==='Publié'?'ok':a.status==='En revue'?'warn':'blue'}">${a.status}</span><button class="btn compact" data-v2-review="${a.id}">Réviser</button></article>`).join('');
    const rr=$('#v2RoiRunbooks');if(rr)rr.innerHTML=[['Disk Capacity Triage','31h','98 runs'],['Network Diagnostic','27h','163 runs'],['Windows Service Recovery','24h','284 runs'],['DNS Resolver Check','19h','211 runs']].map(x=>`<div><span><b>${x[0]}</b><small>${x[2]}</small></span><strong>${x[1]}</strong></div>`).join('');
    const sa=$('#v2SlaAnalytics');if(sa)sa.innerHTML=[['Remote Access',97.8],['Applications',96.3],['Network',97.1],['Workplace',95.4],['Platform',96.9]].map(x=>`<div class="v2-bar-row"><span>${x[0]}</span><b><i style="--w:${x[1]}%"></i></b><strong>${x[1]}%</strong></div>`).join('');
    const tl=$('#v2TeamLoad');if(tl)tl.innerHTML=[['Aina R.','Network / Identity',78],['Noro T.','Applications',63],['Miora A.','Platform / DB',71],['Hery R.','Workplace',54]].map(x=>`<div class="v2-bar-row"><span><b>${x[0]}</b><small>${x[1]}</small></span><b><i style="--w:${x[2]}%"></i></b><strong>${x[2]}%</strong></div>`).join('');
    const tq=$('#v2TeamQuality');if(tq)tq.innerHTML=[['FCR','74%'],['Reopen rate','3,8%'],['CSAT simulé','4,6/5'],['SLA handoff','98,1%']].map(x=>`<div><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');
    renderTrend();
    const rm=$('#v2Roadmap');if(rm)rm.innerHTML=[['Q3 2026','V2 Portfolio','Rules Engine, approvals, problem mgmt','active'],['Q4 2026','Observability+','Service maps, synthetics, SLO',''],['Q1 2027','Integrations','ITSM connectors, webhooks',''],['Q2 2027','AIOps assisté','Correlation scoring, suggestions','']].map(x=>`<article class="${x[3]}"><span>${x[0]}</span><b>${x[1]}</b><p>${x[2]}</p></article>`).join('');
    renderKanban();
    const risk=$('#v2RiskRows');if(risk)risk.innerHTML=state.risks.map(r=>`<tr><td><b>${r.id}</b></td><td>${r.risk}</td><td>${r.impact}</td><td>${r.prob}</td><td>${r.owner}</td><td>${r.mitigation}</td></tr>`).join('');
    const vl=$('#v2VendorList');if(vl)vl.innerHTML=state.vendors.map(v=>`<article><div><b>${v.name}</b><span>${v.service} · renouvellement ${v.renewal}</span></div><div><span>SLA ${v.sla}</span><strong>${v.score}</strong></div><button class="btn compact" data-v2-vendor="${v.name}">Détail</button></article>`).join('');
    const fa=$('#v2FlowArch');if(fa)fa.innerHTML=['Alerte / Ticket','Classification','Rules Engine','Diagnostic dry-run','Approval si changement','Worker simulé','Re-test','Update ITSM','Metrics & Audit'].map((x,i)=>`<button data-v2-flow-step="${i+1}"><span>${String(i+1).padStart(2,'0')}</span><b>${x}</b></button>${i<8?'<i>→</i>':''}`).join('');
    const sc=$('#v2SecurityControls');if(sc)sc.innerHTML=[['RBAC','Rôles séparés analyste / lead / automation'],['Secrets','Références externes, jamais exposées dans la démo'],['Approval','Changement sensible soumis à validation'],['Audit','Chaque action corrélée à un actor et un ticket'],['Network','Workers segmentés des interfaces publiques'],['Safety','Démo publique = simulation uniquement']].map(x=>`<article><b>${x[0]}</b><span>${x[1]}</span></article>`).join('');
    const rb=$('#v2RbacMatrix');if(rb)rb.innerHTML='<div class="tablewrap"><table><thead><tr><th>Rôle</th><th>Voir</th><th>Run dry</th><th>Remédier</th><th>Approuver</th></tr></thead><tbody><tr><td>Analyst</td><td>✓</td><td>✓</td><td>—</td><td>—</td></tr><tr><td>Automation Engineer</td><td>✓</td><td>✓</td><td>✓*</td><td>—</td></tr><tr><td>Support Lead</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td></tr></tbody></table></div>';
    const dp=$('#v2Deploy');if(dp)dp.innerHTML=[['Public UI','Static portfolio','GitHub Pages'],['API','FastAPI concept','Container'],['Workers','Celery concept','Private network'],['Data','PostgreSQL + Redis','Persistent volumes'],['Observability','Prometheus + Grafana','Ops network']].map(x=>`<article><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></article>`).join('');
    const ig=$('#v2Integrations');if(ig)ig.innerHTML=[['ITSM','Tickets, statut, commentaires','REST / webhook'],['Prometheus','Métriques & alertes','Pull / Alertmanager'],['Grafana','Dashboards','Read-only links'],['Identity','Utilisateurs & rôles','OIDC / SSO concept'],['Email/Chat','Notifications','Connector concept'],['CMDB','Services & CI','REST concept']].map(x=>`<article><div><span>${x[0][0]}</span><b>${x[0]}</b></div><p>${x[1]}</p><small>${x[2]}</small><button class="btn compact" data-v2-integration="${x[0]}">Inspecter</button></article>`).join('');
  }

  function renderApprovals(){const el=$('#v2ApprovalList');if(!el)return;$('#v2ApprovalCount').textContent=state.approvals.length;el.innerHTML=state.approvals.length?state.approvals.map(a=>`<article><div><span class="badge warn">${a.risk}</span><b>${a.action}</b><small>${a.target} · demandé par ${a.requester}</small></div><div><button class="btn primary compact" data-v2-approve="${a.id}">Approuver</button><button class="btn compact" data-v2-reject="${a.id}">Refuser</button></div></article>`).join(''):'<div class="empty-v2">Aucune approbation en attente.</div>'}
  function renderMetricSpark(){const el=$('#v2MetricSpark');if(!el)return;const vals=[32,46,41,58,51,64,72,61,79,68,74,83,77,88,69,63,71,76,81,73];el.innerHTML=vals.map(v=>`<span style="--h:${v}%"></span>`).join('')}
  function renderTrend(){const el=$('#v2TrendChart');if(!el)return;const vals=[82,76,71,68,64,61,58,55,51,48,46,44];el.innerHTML=vals.map((v,i)=>`<span style="--h:${v}%"><b>${v}</b><i>S${i+1}</i></span>`).join('')}
  function renderKanban(){const el=$('#v2Kanban');if(!el)return;el.innerHTML=Object.entries(state.tasks).map(([lane,items])=>`<section class="v2-lane" data-v2-lane="${lane}"><h4>${lane}<em>${items.length}</em></h4>${items.map(x=>`<button class="v2-task" data-v2-task="${safe(x)}" data-v2-from="${lane}"><b>${safe(x)}</b><small>SupportOps V2</small><span>⋯</span></button>`).join('')}</section>`).join('')}
  function setV2Tab(page,view,btn){const root=$(`#${page}`);if(!root)return;$$('.v2-tabs button',root).forEach(b=>b.classList.toggle('active',b===btn));$$('.v2-panel',root).forEach(p=>p.classList.toggle('active',p.dataset.v2Panel===view));renderV2();}
  function exportCsv(kind){const rows = kind==='executions' ? [['Run','Runbook','Cible','Acteur','Statut','Durée','Heure'],...state.executions.map(x=>[x.id,x.runbook,x.target,x.by,x.status,x.duration,x.time])] : kind==='trends' ? [['Semaine','Index MTTR'],...[82,76,71,68,64,61,58,55,51,48,46,44].map((v,i)=>[`S${i+1}`,v])] : [['Incident','Type','Cause'],['INC-1988','P2','Attente fournisseur'],['INC-1962','P3','Mauvaise catégorisation']];const csv=rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`supportops-${kind}-demo.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);toast('Export CSV fictif généré');}

  function init(){
    Object.keys(tabs).forEach(installTabs);
    const nav=$('.side-nav'); if(nav && !$('#v2VersionBadge')) nav.insertAdjacentHTML('afterend','<div class="v2-version" id="v2VersionBadge"><span>V2</span><b>Interactive Ops Lab</b><small>Tous les modules sont explorables</small></div>');
    renderV2();
  }

  document.addEventListener('click',e=>{
    const tab=e.target.closest('[data-v2-tab]');if(tab){setV2Tab(tab.dataset.v2Page,tab.dataset.v2Tab,tab);return}
    const appr=e.target.closest('[data-v2-approve],[data-v2-reject]');if(appr){const id=appr.dataset.v2Approve||appr.dataset.v2Reject;state.approvals=state.approvals.filter(x=>x.id!==id);renderApprovals();toast(appr.dataset.v2Approve?'Remédiation approuvée dans la simulation':'Demande refusée dans la simulation');return}
    const tog=e.target.closest('[data-v2-toggle-rule]');if(tog){const r=state.rules.find(x=>x.id===tog.dataset.v2ToggleRule);if(r){r.active=!r.active;renderV2();toast(`Règle ${r.active?'activée':'désactivée'} dans la démo`)}return}
    const ex=e.target.closest('[data-v2-export]');if(ex){exportCsv(ex.dataset.v2Export);return}
    if(e.target.closest('[data-v2-sim-run]')){state.executions.unshift({id:`RUN-${8832+state.executions.length}`,runbook:'Network Diagnostic',target:'INC-DEMO',by:'Utilisateur démo',status:'Succès',duration:'00:39',time:new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})});renderV2();toast('Exécution simulée ajoutée');return}
    if(e.target.closest('[data-v2-new-rule]')){modal('Nouvelle règle d’automatisation','<div class="formgrid"><label>Nom<input id="v2RuleName" value="Nouvelle règle de diagnostic"></label><label>Trigger<input id="v2RuleTrigger" value="category=Application"></label><label>Runbook<select><option>HTTP Synthetic Probe</option><option>Network Diagnostic</option></select></label><label>Mode<select><option>Auto diagnostic</option><option>Approval required</option></select></label></div><p class="muted">Configuration fictive : aucun worker réel n’est contacté.</p>','<button class="btn primary" data-v2-save-rule>Créer la règle</button><button class="btn" data-close-modal>Annuler</button>');return}
    if(e.target.closest('[data-v2-save-rule]')){state.rules.unshift({id:`RULE-${30+state.rules.length}`,name:$('#v2RuleName')?.value||'Nouvelle règle',trigger:$('#v2RuleTrigger')?.value||'trigger',runbook:'HTTP Synthetic Probe',mode:'Auto diagnostic',active:true});$('#modalBg').hidden=true;renderV2();toast('Règle ajoutée à la simulation');return}
    const rule=e.target.closest('[data-v2-rule]');if(rule){const r=state.rules.find(x=>x.id===rule.dataset.v2Rule);if(r)modal(r.id,`<div class="kv"><div><span>Nom</span><b>${r.name}</b></div><div><span>Déclencheur</span><b>${r.trigger}</b></div><div><span>Runbook</span><b>${r.runbook}</b></div><div><span>Mode</span><b>${r.mode}</b></div></div><p class="muted">Édition de démonstration uniquement.</p>`);return}
    const dep=e.target.closest('[data-v2-dependency]');if(dep){$('#v2DependencyDetail').innerHTML=`<b>${safe(dep.dataset.v2Dependency)}</b><span>Dépendances simulées : API, datastore, monitoring et réseau. Cliquez sur un autre nœud pour comparer l’impact.</span>`;$$('[data-v2-dependency]').forEach(b=>b.classList.toggle('active',b===dep));return}
    const probe=e.target.closest('[data-v2-probe]');if(probe){toast(`Probe « ${probe.dataset.v2Probe} » simulée : 200 OK · 126 ms`);return}
    if(e.target.closest('[data-v2-new-probe],[data-v2-new-route],[data-v2-new-silence],[data-v2-new-policy],[data-v2-new-known],[data-v2-new-milestone],[data-v2-new-risk],[data-v2-new-major],[data-v2-new-postmortem]')){modal('Création de démonstration','<div class="formgrid"><label>Nom<input value="Nouvel élément SupportOps"></label><label>Owner<input value="Utilisateur démo"></label><label class="wide">Description<textarea>Élément fictif ajouté pour explorer le workflow V2.</textarea></label></div>','<button class="btn primary" data-v2-demo-save>Enregistrer dans la démo</button><button class="btn" data-close-modal>Annuler</button>');return}
    if(e.target.closest('[data-v2-demo-save]')){$('#modalBg').hidden=true;toast('Élément enregistré uniquement dans la démo');return}
    const problem=e.target.closest('[data-v2-problem]');if(problem){const p=state.problems.find(x=>x.id===problem.dataset.v2Problem);if(p)modal(`${p.id} · ${p.title}`,`<div class="kv"><div><span>Incidents liés</span><b>${p.incidents}</b></div><div><span>Cause probable</span><b>${p.root}</b></div><div><span>Statut</span><b>${p.status}</b></div></div><p>Étapes proposées : revue des incidents, hypothèse de cause, validation, Known Error puis action corrective.</p>`);return}
    const art=e.target.closest('[data-v2-article],[data-v2-review]');if(art){const id=art.dataset.v2Article||art.dataset.v2Review;const a=state.articles.find(x=>x.id===id);if(a)modal(`${a.id} · ${a.title}`,`<div class="kv"><div><span>Type</span><b>${a.type}</b></div><div><span>Owner</span><b>${a.owner}</b></div><div><span>Statut</span><b>${a.status}</b></div><div><span>Prochaine revue</span><b>${a.review}</b></div></div>`,`<button class="btn primary" data-v2-publish="${a.id}">Marquer publié</button><button class="btn" data-close-modal>Fermer</button>`);return}
    const pub=e.target.closest('[data-v2-publish]');if(pub){const a=state.articles.find(x=>x.id===pub.dataset.v2Publish);if(a)a.status='Publié';$('#modalBg').hidden=true;renderV2();toast('Article publié dans la simulation');return}
    const task=e.target.closest('[data-v2-task]');if(task){const lanes=Object.keys(state.tasks),from=task.dataset.v2From,name=task.dataset.v2Task;const idx=lanes.indexOf(from),to=lanes[Math.min(idx+1,lanes.length-1)];modal(`Tâche · ${name}`,`<p>Déplacer cette tâche de <b>${from}</b> vers <b>${to}</b> ?</p><p class="muted">Le board est interactif uniquement en mémoire locale.</p>`,`<button class="btn primary" data-v2-move-task="${safe(name)}" data-v2-from-lane="${from}" data-v2-to-lane="${to}">Déplacer</button><button class="btn" data-close-modal>Annuler</button>`);return}
    const move=e.target.closest('[data-v2-move-task]');if(move){const {v2MoveTask:name,v2FromLane:from,v2ToLane:to}=move.dataset;state.tasks[from]=state.tasks[from].filter(x=>x!==name);state.tasks[to].push(name);$('#modalBg').hidden=true;renderKanban();toast(`Tâche déplacée vers ${to}`);return}
    if(e.target.closest('[data-v2-new-task]')){modal('Nouvelle tâche','<div class="formgrid"><label>Titre<input id="v2TaskTitle" value="Nouvelle amélioration SupportOps"></label><label>Lane<select id="v2TaskLane"><option>Backlog</option><option>Todo</option><option>Progress</option></select></label></div>','<button class="btn primary" data-v2-save-task>Ajouter</button><button class="btn" data-close-modal>Annuler</button>');return}
    if(e.target.closest('[data-v2-save-task]')){const l=$('#v2TaskLane')?.value||'Backlog',n=$('#v2TaskTitle')?.value||'Nouvelle tâche';state.tasks[l].unshift(n);$('#modalBg').hidden=true;renderKanban();toast('Tâche ajoutée au board');return}
    const vendor=e.target.closest('[data-v2-vendor]');if(vendor){const v=state.vendors.find(x=>x.name===vendor.dataset.v2Vendor);if(v)modal(v.name,`<div class="kv"><div><span>Service</span><b>${v.service}</b></div><div><span>SLA</span><b>${v.sla}</b></div><div><span>Renouvellement</span><b>${v.renewal}</b></div><div><span>Score</span><b>${v.score}</b></div></div><p class="muted">Données fournisseur entièrement fictives.</p>`);return}
    const integ=e.target.closest('[data-v2-integration]');if(integ){modal(`Intégration · ${integ.dataset.v2Integration}`,`<div class="v2-integration-modal"><span>Auth</span><b>Token / OIDC conceptuel</b><span>Mode</span><b>Lecture / webhook simulé</b><span>Statut</span><b>Demo connector</b></div><p class="muted">Aucune connexion externe n'est réalisée par cette démo.</p>`);return}
    const flow=e.target.closest('[data-v2-flow-step]');if(flow){toast(`Étape ${flow.dataset.v2FlowStep} sélectionnée dans le flux`);return}
    if(e.target.closest('[data-v2-copy-query]')){const q=$('#v2PromQuery')?.textContent||'';navigator.clipboard?.writeText(q).then(()=>toast('Requête copiée')).catch(()=>toast('Requête prête à copier'));return}
    const range=e.target.closest('[data-v2-range],[data-v2-analytics-range]');if(range){const group=range.parentElement;$$('button',group).forEach(b=>b.classList.toggle('active',b===range));toast(`Période ${range.dataset.v2Range||range.dataset.v2AnalyticsRange+'j'} sélectionnée`);return}
    const generic=e.target.closest('[data-v2-major],[data-v2-postmortem],[data-v2-breach],[data-v2-correlation],[data-v2-route],[data-v2-action-detail]');if(generic){const label=generic.dataset.v2Major||generic.dataset.v2Postmortem||generic.dataset.v2Breach||generic.dataset.v2Correlation||generic.dataset.v2Route||generic.dataset.v2ActionDetail;modal('Détail SupportOps V2',`<p><b>${safe(label)}</b></p><p>Cette vue illustre un workflow opérationnel approfondi : ownership, statut, chronologie, SLA et action suivante.</p><p class="muted">Données fictives de portfolio.</p>`);return}
  });

  document.addEventListener('change',e=>{if(e.target.id==='v2MetricSelect'){const q={support_mttr_seconds:'histogram_quantile(0.95, support_mttr_seconds_bucket)',support_sla_compliance:'avg_over_time(support_sla_compliance[30m])',automation_runs_total:'rate(automation_runs_total[5m])',service_availability:'avg_over_time(service_availability[1h])'};$('#v2PromQuery').textContent=q[e.target.value]||e.target.value;renderMetricSpark()}});

  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
